- include_tasks: instance.yml
  when: >
    redmine_task_instance != ''
    and (mysql_replication_role is undefined or mysql_replication_role == 'master')
    and sync_master is undefined
  tags: redmine
