- name: Create recurrent tasks
  shell: bash -lc "bundle exec rake redmine:recur_tasks"
  args:
    chdir: '{{ redmine_task_dir }}'
  become: "{{ 'true' if redmine_task_user != '' else 'false' }}"
  become_user: '{{ redmine_task_user | default(omit) }}'
  environment:
    RAILS_ENV: '{{ rails_env }}'
    PATH: '/usr/local/bin:/usr/bin:/bin:{{ redmine_task_dir }}/.rvm/bin'
  register: recur_tasks

- name: Output of recur_tasks
  debug: var=recur_tasks.stdout_lines
  when: recur_tasks.changed
