- name: Run whenever for issue-open-date
  shell: bash -lc "bundle exec whenever -i redmine_issue_open_date -f plugins/redmine_issue_open_date/config/schedule.rb"
  args:
    chdir: '{{ redmine_task_dir }}'
  become: "{{ true if redmine_task_user != '' else false }}"
  become_user: '{{ redmine_task_user | default(omit) }}'
  environment:
    RAILS_ENV: '{{ rails_env }}'
    PATH: '/usr/local/bin:/usr/bin:/bin:{{ redmine_task_dir }}/.rvm/bin'
  register: issue_open_date

- name: Output of whenever
  debug: var=issue_open_date.stdout_lines
  when: issue_open_date.changed
