# tasks for https://github.com/AlphaNodes/redmine_postgresql_search

- name: Update search index
  shell: bash -lc "bundle exec rake redmine_postgresql_search:update_index"
  args:
    chdir: '{{ redmine_task_dir }}'
  become: "{{ true if redmine_task_user != '' else false }}"
  become_user: '{{ redmine_task_user | default(omit) }}'
  environment:
    RAILS_ENV: '{{ rails_env }}'
    PATH: '/usr/local/bin:/usr/bin:/bin:{{ redmine_task_dir }}/.rvm/bin'
  register: update_index

- name: Output of update_index
  debug: var=update_index.stdout_lines
  when: update_index.changed
