- name: Send reminder mail
  shell: bash -lc "bundle exec rake redmine:send_reminders days={{ redmine_task_reminder_day }}"
  args:
    chdir: '{{ redmine_task_dir }}'
  become: "{{ 'true' if redmine_task_user != '' else 'false' }}"
  become_user: '{{ redmine_task_user | default(omit) }}'
  register: reminder
  changed_when: reminder.stdout_lines | length
  environment:
    RAILS_ENV: '{{ rails_env }}'
    PATH: '/usr/local/bin:/usr/bin:/bin:{{ redmine_task_dir }}/.rvm/bin'

- name: Output of reminder
  debug: var=reminder.stdout_lines
  when: reminder.changed
